# training parameters
################################################################################
train:
  pipeline: "Fid"        # model name 
  loss: "xentropy"       # must be either xentropy or iou
  max_epochs: 50
  batch_size: 6          # batch size
  report_batch: 10       # every x batches, report loss
  report_epoch: 1        # every x epochs, report validation set
  epsilon_w: 0.001       # class weight w = 1 / (content + epsilon_w)
  save_summary: False    # Summary of weight histograms for tensorboard
  save_scans: False      # False doesn't save anything, True saves some sample images 
                         # (one per batch of the last calculated batch) in log folder
  show_scans: False      # show scans during training
  workers: 12            # number of threads to get data

  syncbn: True           # sync batchnorm
  act: LeakyReLU         # act layer

  optimizer: "adam"  # sgd or adam
  sgd:
    momentum: 0.9          # sgd momentum
    w_decay: 0.0001        # weight decay

  scheduler: "consine"  # "consine" or "warmup"
  consine:
    min_lr: 0.00001
    max_lr: 0.00200
    first_cycle: 50
    cycle: 2
    wup_epochs: 1
    gamma: 1.0
  warmup:
    lr: 0.01             # learning rate
    wup_epochs: 1        # warmup during first XX epochs (can be float)
    lr_decay: 0.99       # learning rate decay per epoch after initial cycle (from min lr)
    momentum: 0.9          # sgd momentum

  aux_loss:
    use: False
    lamda: [0.5, 1.0, 1.0]
  
  # for mos
  residual: False # This needs to be the same as in the dataset params below!
  n_input_scans: 8 # This needs to be the same as in the dataset params below!

################################################################################
# postproc parameters
################################################################################
post:
  CRF:
    use: False
    train: True
    params: False # this should be a dict when in use
  KNN:
    use: True # This parameter default is false
    params:
      knn: 7
      search: 7
      sigma: 1.0
      cutoff: 2.0

################################################################################
# classification head parameters
################################################################################
# dataset (to find parser)
dataset:
  labels: "kitti"
  scans: "kitti"
  max_points: 35000 # max of any scan in dataset
  sensor:
    name: "HDL32"
    type: "spherical" # projective
    fov_up: 10
    fov_down: -30
    img_prop:
      width:  1024
      height: 32
    img_means: #range,x,y,z,signal
      - 1.7835
      - 0.0325
      - 0.1707
      - 0.0283
      - 2.7328
    img_stds: #range,x,y,z,signal
      - 9.5803
      - 6.7944
      - 8.1486
      - 1.1270
      - 17.4203
    # img_means: #range,x,y,z,signal
    #   - 12.12
    #   - 10.88
    #   - 0.23
    #   - -1.04
    #   - 0.21
    # img_stds: #range,x,y,z,signal
    #   - 12.32
    #   - 11.47
    #   - 6.91
    #   - 0.86
    #   - 0.16
      
    # for mos
    n_input_scans: 8  # This needs to be the same as in the backbone params above!
    residual: False    # This needs to be the same as in the backbone params above!
    transform: False  # tranform the last n_input_scans - 1 frames before concatenation
    use_normal: False # if use normal vector as channels of range image
